### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tianshaokai** [AndyJennifer/SimpleEyes#4]
2019-08-28 13:45:27.653 6881-6881/com.jennifer.andy.simpleeyes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jennifer.andy.simpleeyes, PID: 6881
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jennifer.andy.simpleeyes/com.jennifer.andy.simpleeyes.ui.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_category_recycler. Make sure other views do not use the same id.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_category_recycler. Make sure other views do not use the same id.
        at android.view.View.onRestoreInstanceState(View.java:17731)
        at android.view.View.dispatchRestoreInstanceState(View.java:17706)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3745)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
        at android.view.View.restoreHierarchyState(View.java:17684)
        at android.support.v4.app.Fragment.restoreViewState(Fragment.java:494)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1486)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at com.jennifer.andy.simpleeyes.ui.base.BaseAppCompatActivity.onStart(BaseAppCompatActivity.kt:51)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7029)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699) 
        at android.app.ActivityThread.-wrap18(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by tianshaokai** [comment]
有个anr问题，给作者发了一封邮件，附件是traces.txt 文件

**Comment by AndyJennifer** [comment]
> 有个anr问题，给作者发了一封邮件，附件是traces.txt 文件

关于RecyclerView ID重复的问题，请更新项目到最新的版本。关于ANR的问题官方也没有做出解释。具体链接: [https://github.com/bilibili/ijkplayer/issues?utf8=✓&q=Anr](https://github.com/bilibili/ijkplayer/issues?utf8=✓&q=Anr)

**Comment by tianshaokai** [comment]
这个id rv_category_recycler 重复，我一直没有理解代码crash 的原因，还望作者做出解释一下

**Comment by tianshaokai** [comment]
2019-08-28 18:55:20.250 15130-15130/com.jennifer.andy.simpleeyes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jennifer.andy.simpleeyes, PID: 15130
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jennifer.andy.simpleeyes/com.jennifer.andy.simpleeyes.ui.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_home_recycler. Make sure other views do not use the same id.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_home_recycler. Make sure other views do not use the same id.
        at android.view.View.onRestoreInstanceState(View.java:17731)
        at android.view.View.dispatchRestoreInstanceState(View.java:17706)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3745)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
        at android.view.View.restoreHierarchyState(View.java:17684)
        at android.support.v4.app.Fragment.restoreViewState(Fragment.java:494)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1486)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at com.jennifer.andy.simpleeyes.ui.base.BaseAppCompatActivity.onStart(BaseAppCompatActivity.kt:51)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7029)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

还是有问题，我一直没理解为啥会出现相同的id

**Comment by tianshaokai** [comment]
2019-08-28 18:57:47.057 15470-15470/com.jennifer.andy.simpleeyes D/IjkVideoView: MEDIA_INFO_AUDIO_RENDERING_START:
2019-08-28 18:57:47.101 15470-15572/com.jennifer.andy.simpleeyes D/IJKMEDIA: FFP_MSG_VIDEO_RENDERING_START:
2019-08-28 18:57:47.108 15470-15470/com.jennifer.andy.simpleeyes I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
2019-08-28 18:57:47.109 15470-15470/com.jennifer.andy.simpleeyes D/IjkVideoView: MEDIA_INFO_VIDEO_RENDERING_START:
2019-08-28 18:57:47.169 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.178 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.210 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.272 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.314 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.344 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.371 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.421 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.462 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.498 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.524 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.569 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.607 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.645 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.685 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.725 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.769 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.805 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.844 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.888 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:47.899 15470-15470/com.jennifer.andy.simpleeyes W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void com.jennifer.andy.simpleeyes.player.IjkMediaController.updateProgressAndTime(com.jennifer.andy.simpleeyes.player.event.VideoProgressEvent)' on a null object reference
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-28 18:57:47.900 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-08-28 18:57:47.901 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-08-28 18:57:47.901 15470-15470/com.jennifer.andy.simpleeyes W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jennifer.andy.simpleeyes.player.IjkMediaController.updateProgressAndTime(com.jennifer.andy.simpleeyes.player.event.VideoProgressEvent)' on a null object reference
2019-08-28 18:57:47.901 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at com.jennifer.andy.simpleeyes.player.IjkVideoView$9.accept(IjkVideoView.java:1074)
2019-08-28 18:57:47.901 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at com.jennifer.andy.simpleeyes.player.IjkVideoView$9.accept(IjkVideoView.java:1064)
2019-08-28 18:57:47.901 15470-15470/com.jennifer.andy.simpleeyes W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
2019-08-28 18:57:47.901 15470-15470/com.jennifer.andy.simpleeyes W/System.err: 	... 10 more
2019-08-28 18:57:47.925 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:47.970 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.005 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.052 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.089 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.124 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.166 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.221 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.256 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.285 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.328 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.366 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.405 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.445 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.484 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.524 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.565 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.605 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.644 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.694 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.724 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.764 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.805 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:48.846 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.884 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.924 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:48.965 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:49.004 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:49.044 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:49.085 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:49.124 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:49.175 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:49.205 15470-15579/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:49.246 15470-15580/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
2019-08-28 18:57:49.284 15470-15581/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:49.326 15470-15582/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
2019-08-28 18:57:49.368 15470-15578/com.jennifer.andy.simpleeyes D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0

有空指针的情况

**Comment by tianshaokai** [comment]
重复Id的问题，难道跟我修改本地的编译版本有关系吗，因为环境我问题，我改成了compileSdkVersion 28，support 库改成了28.0.0

**Comment by tianshaokai** [comment]
感觉support 库与androidx.core:core-ktx:0.3 库有兼容问题，不知道作者那里有没有这种问题

**Comment by AndyJennifer** [comment]
> 感觉support 库与androidx.core:core-ktx:0.3 库有兼容问题，不知道作者那里有没有这种问题

androidx.core:core这个包是为以后迁移Androidx库做准备的。AndoirX和Android support这两个库是不兼容。为了避免给大家造成困扰，现在我准备移除了。关于空指针的问题，能具体描述一下情况吗？

**Comment by tianshaokai** [comment]
2019-08-29 12:37:39.224 19269-19269/com.jennifer.andy.simpleeyes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jennifer.andy.simpleeyes, PID: 19269
    java.lang.RuntimeException: Unable to stop activity {com.jennifer.andy.simpleeyes/com.jennifer.andy.simpleeyes.ui.video.VideoDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jennifer.andy.simpleeyes.player.IjkMediaController.hide()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4345)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jennifer.andy.simpleeyes.player.IjkMediaController.hide()' on a null object reference
        at com.jennifer.andy.simpleeyes.player.IjkVideoView.stopPlayback(IjkVideoView.java:336)
        at com.jennifer.andy.simpleeyes.ui.video.VideoDetailActivity.onStop(VideoDetailActivity.kt:289)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1375)
        at android.app.Activity.performStop(Activity.java:7191)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4340)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2019-08-29 12:37:39.227 1678-6832/system_process W/ActivityManager:   Force finishing activity com.jennifer.andy.simpleeyes/.ui.MainActivity

打开第一个视频后，滑动列表再打开一个视频，然后点击返回

**Comment by tianshaokai** [comment]
不知道为什么，总感觉列表特别卡，滑动的不是很流畅

**Comment by AndyJennifer** [comment]
> 不知道为什么，总感觉列表特别卡，滑动的不是很流畅

卡顿的问题，开启了预加载，在滑动到倒数第五个的时候，开始加载更多。

**Comment by tianshaokai** [comment]
我说的卡顿 感觉像是滑动导致的卡顿，因为我是用的模拟器，每次滑动时感觉就会回到之前的位置，很奇怪，我对这块不熟 希望可以和作者多交流一下
